const initApp = () => {
  console.log('Initializing application');
};

try {
  initApp();
} catch (e) {
  console.log(`Error occurred: ${e}`);
}
